---
title: "Example_HydroCODA"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Example_HydroCODA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# MAIN EXAMPLE
## Clusterirn analysis 

```{r echo=TRUE, fig.align= "center", fig.height= 4, fig.width= 8}
library(HydroCODA)
# Load water chemical concentrations database and shapes for the geology faults and study area
data(Balance, geological_units, faults, Area_data)

# Definition of hydrochemical clusters using the CoDA approach
Dataclust <- waterclust(Balance, height = 50, typ = 2, chem.name = FALSE)

```
## Clusterirn analysis 
The `Stiffclust` function ....
Aqui falta hablar de lo se muestra
```{r echo=TRUE, fig.align= "center", fig.height= 4, fig.width= 8}
library(HydroCODA)
# Draw Stiff diagrams based on the defined clustering
Stiffclust(Dataclust, plt = TRUE)
```
## Principal Component Analysis
...

```{r echo=TRUE, fig.align= "center", fig.height= 4, fig.width= 8}
# Run the Principal Component Analysis using the CoDA approach and draw the biplot
PCAcoda(Dataclust, comp1 = 1, comp2 = 2)
```

## Interactive map

```{r echo=TRUE, fig.align= "center", fig.height= 4, fig.width= 8}
# Draw the geographical distribution of water samples showing the assigned cluster
mapaclust(Dataclust, crsprj = 4326, Area = Area_data, 
          Geology = geological_units, Faults =faults, mapout = FALSE, shp_field = "SimboloUC", Filename = NULL)
```